Completa objetivo 0
Asmilex/IV pull request #1
Opened 2021-09-17 11:55 UTC by Asmilex

Este pull request completa el objetivo 0.:

- Se añade gitignore.
- Se completa el README con la descripción del proyecto.

2021-09-17 17:47 UTC, JJ requested changes

2021-09-17 17:47 UTC, JJ commented on README.md
> +En mi caso, acabo poniendo recordatorios en Telegram mediante mensajes programados. Tanto en mis mensajes guardados como en un grupo privado que tengo de la universidad.
A partir de aquí, no corresponde a este hito.

2021-09-17 17:47 UTC, JJ commented on README.md
> +La mayoría de las aplicaciones de *TODO-list* no funcionan. Requieren tiempo de gestión, que accedas continuamente a ellas, y que organices correctamente tus objetivos. Al final, todas acaban sin usa
Formulas un problema más o menos con claridad. Quizás deberías haberte quedado aquí.

2021-09-19 09:33 UTC, Asmilex commented on README.md
> +La mayoría de las aplicaciones de *TODO-list* no funcionan. Requieren tiempo de gestión, que accedas continuamente a ellas, y que organices correctamente tus objetivos. Al final, todas acaban sin usa
Voy a mover la descripción a una nueva rama, dev, en la que además iré desarrollando la aplicación mientras tanto 👍🏼

2021-09-19 09:36 UTC, merged

2021-09-19 09:48 UTC, JJ commented
Por favor, no fusiones hasta que no esté aprobado.

2021-09-19 10:00 UTC, Asmilex commented
Ay, al haber estado el otro PR mergeado había entendido que este estaba listo. ¿Revierto?

2021-09-19 10:31 UTC, JJ commented
Revertir crea otro PR diferente, y este seguirá cerrado, por lo que tendrás que volver a abrir otro PR, que tendré que aprobar...
Digamos que está aprobado, pero te agradecería que no vuelvas a hacerlo.

2021-09-19 10:31 UTC, JJ reviewed
:+1:

2021-09-19 10:40 UTC, Asmilex commented
Ok, lo tendré en cuenta para la próxima, siento el lío. Cuestión de acostumbrarme a trabajar. ¡Muchas gracias!